class Config:
    IMAGE_SIZE=(512,512)
    NUM_CLASSES=12
    BATCH_SIZE=4
    CLASS_NAMES=[
        "background",
        "person",
        "bike",
        "car",
        "drone",
        "boat",
        "animal",
        "obstacle",
        "construction",
        "vegetation",
        "road",
        "sky",
    ]
    DATA_ROOT="aeroscapes"
    HIDDEN_DIM=96
    LAYERS=(2,2,6,2)
    HEADS=(3,6,12,24)
    HEAD_DIM=32
    WINDOW_SIZE=8
    DOWNSCALING_FACTORS=(4,2,2,2)
    DROPOUT=0.1
    DROP_PATH_RATE=0.1
    DECODER_DIM=256
    BATCH_SIZE=4
    NUM_EPOCHS=100
    ENCODER_LR=6e-5
    DECODER_LR=6e-4
    WEIGHT_DECAY=0.01
    GRAD_CLIP=1.0
    CHECKPOINT_DIR="checkpoints"